#!/bin/bash
# Quick command reference for pushing to GitHub and deploying

echo "🚀 Quick Start Guide"
echo "===================="
echo ""
echo "📝 STEP 1: Commit Your Changes"
echo "--------------------------------"
echo "git add ."
echo "git commit -m 'Clean up project for production'"
echo ""
echo "📤 STEP 2: Push to GitHub"
echo "-------------------------"
echo "./push-to-github.sh"
echo ""
echo "OR manually:"
echo "git init"
echo "git branch -M main"
echo "git remote add origin https://github.com/YOUR_USERNAME/masjid-studentski-grad.git"
echo "git push -u origin main"
echo ""
echo "🌐 STEP 3: Deploy Backend (Railway)"
echo "------------------------------------"
echo "1. Go to https://railway.app"
echo "2. New Project → Deploy from GitHub"
echo "3. Add PostgreSQL database"
echo "4. Set environment variables (see backend/.env.example)"
echo "5. Deploy!"
echo ""
echo "🎨 STEP 4: Deploy Frontend (Vercel)"
echo "------------------------------------"
echo "1. Go to https://vercel.com"
echo "2. Import from GitHub"
echo "3. Root directory: frontend"
echo "4. Set environment variables (see frontend/.env.example)"
echo "5. Deploy!"
echo ""
echo "⚙️  STEP 5: Post-Deployment"
echo "---------------------------"
echo "1. Configure Stripe webhooks"
echo "2. Test donations"
echo "3. Create admin user"
echo "4. Test all features"
echo ""
echo "📚 Full guide: DEPLOYMENT_GUIDE.md"
echo ""
